# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Amanuel Melekin
#tagline:          
description:      'welp, I see now'
url:              http://amanmelekin.github.io
baseurl:          /amanmelekin.github.io/


author:
    gravatar_md5:   bdc47572bf329aace9009b582c9f780e
    name:           'Amanuel Melekin'
    linkedin:       tembo
    github:         amanmelekin
    email:          amelekin@gmail
    twitter:        AmanDmam
    
paginate:         5
plugins: [jekyll-paginate, jekyll-gist]
paginate_path: "page:num"

excerpt_separator: <!--more-->
# Custom vars
version:          2.1.0

excerpt_separator: '<!--more-->'

