# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column' 
url:              
baseurl:          

author:
  name:           'manuel'


paginate:         5
plugins: [jekyll-paginate, jekyll-gist]

# Custom vars
version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
