# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Amanuel Melekin
#tagline:          
description:      'welp, I see now'
url:              http://swala.github.io
baseurl:          /


author:
    gravatar_md5:   bdc47572bf329aace9009b582c9f780e
    name:           'Amanuel Melekin'
    linkedin:       tembo
    github:         swala
    email:          amelekin@gmail
    twiter:         AmanDmam
    
paginate:         5
plugins: [jekyll-paginate, jekyll-gist]
paginate_path: "page:num"

# Custom vars
version:          2.1.0

excerpt_separator: '<!--more-->'

