# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Amanuel Melekin
        
description:      'Social Systems & Data'
url:              http://azmelekin.com/

baseurl:          /azmelekin.com/


author:
    gravatar_md5:   bdc47572bf329aace9009b582c9f780e
    name:           'Amanuel Melekin'
    linkedin:       amanuelmelekin
    github:         azmelekin
    email:          amelekin@gmail
    twitter:        AmanDmam
    
paginate:         5
plugins: [jekyll-paginate, jekyll-gist]
paginate_path: "page:num"

excerpt_separator: '<!--more-->'

# Custom vars
version:          2.1.0


